/*
-- Query: SELECT * FROM con_doDB.advisors
-- Date: 2019-04-26 11:46
*/
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (1,'Rogan Castillo','sapien.Aenean@tellus.co.uk','Lockport HS','Security Council','United States');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (2,'Arsenio Cruz','viverra.Donec.tempus@Quisque.edu','Lockport HS','ECOSOC','United States');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (3,'Dante Bond','malesuada@felis.org','Lockport HS','UN GA1','United States');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (4,'Peter Farrell','nunc.Quisque@seddui.net','Lockport HS','UN GA2','United States');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (5,'Griffin Yates','nisl@aliquetsem.org','Lockport HS','IAEA','United States');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (6,'Reece Simon','rutrum@fringillacursuspurus.edu','Lockport HS','Security Council','France');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (7,'Cyrus Mullins','malesuada@imperdietullamcorperDuis.ca','Lockport HS','ECOSOC','France');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (8,'Elijah Riley','dui.Fusce.diam@accumsan.co.uk','Lockport HS','UN GA1','France');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (9,'Conan Hicks','faucibus.orci.luctus@famesac.com','Lockport HS','UN GA2','France');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (10,'Octavius Joyce','lacus@consequatdolorvitae.co.uk','Lockport HS','IAEA','France');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (11,'Avram Caldwell','cursus.Nunc.mauris@NullaaliquetProin.ca','Benet Academy','Security Council','United Kingdom');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (12,'Russell Holcomb','malesuada.ut.sem@convallisin.ca','Benet Academy','ECOSOC','United Kingdom');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (13,'Coby Clemons','sagittis@est.net','Benet Academy','UN GA1','United Kingdom');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (14,'Colin Foster','sem.consequat@DuisgravidaPraesent.edu','Benet Academy','UN GA2','United Kingdom');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (15,'Cooper Terrell','torquent@Suspendisseac.ca','Benet Academy','IAEA','United Kingdom');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (16,'Baker Solis','Ut.tincidunt.vehicula@neque.ca','Benet Academy','Security Council','Senegal');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (17,'Damon Reilly','enim.condimentum@massaInteger.co.uk','Benet Academy','ECOSOC','Senegal');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (18,'Colby Pitts','Nunc@justo.com','Benet Academy','UN GA1','Senegal');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (19,'Murphy Horton','magna@leo.edu','Benet Academy','UN GA2','Senegal');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (20,'Harper Weaver','Curabitur.sed.tortor@Pellentesque.net','Benet Academy','IAEA','Senegal');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (21,'Kane Mccullough','ut.dolor.dapibus@Morbi.ca','North Shore Country Day','Security Council','Federated States of Micronesia');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (22,'Leonard Gomez','enim@vulputatemauris.net','North Shore Country Day','ECOSOC','Federated States of Micronesia');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (23,'Phillip Merrill','est.Nunc@nunc.net','North Shore Country Day','UN GA1','Federated States of Micronesia');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (24,'Forrest Hickman','vestibulum.massa@Etiamgravidamolestie.ca','North Shore Country Day','UN GA2','Federated States of Micronesia');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (25,'Edward Lindsay','orci@purusinmolestie.edu','North Shore Country Day','IAEA','Federated States of Micronesia');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (26,'Eric Kidd','interdum.ligula.eu@aneque.edu','Whitney Young','Security Council','Russian Federation');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (27,'Tyrone Malone','sed.dui.Fusce@ipsum.edu','Whitney Young','ECOSOC','Russian Federation');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (28,'Blaze Whitney','arcu.iaculis@Aenean.com','Whitney Young','UN GA1','Russian Federation');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (29,'Mannix Patterson','adipiscing.non@sem.com','Whitney Young','UN GA2','Russian Federation');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (30,'Burton Pierce','quis.diam.luctus@rutrumloremac.com','Whitney Young','IAEA','Russian Federation');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (31,'Ahmed Dawson','cursus@rutrummagnaCras.co.uk','Whitney Young','Security Council','Mexico');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (32,'Emmanuel Evans','et.magnis@semsemper.ca','Whitney Young','ECOSOC','Mexico');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (33,'Vernon Hooper','amet.diam.eu@Integertincidunt.edu','Whitney Young','UN GA1','Mexico');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (34,'Craig Skinner','at.risus.Nunc@mieleifendegestas.edu','Whitney Young','UN GA2','Mexico');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (35,'Rahim Bush','eu@Aliquam.com','Whitney Young','IAEA','Mexico');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (36,'Dustin Frost','Sed.et.libero@Aliquameratvolutpat.ca','Elk Grove HS','Security Council','China');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (37,'Marsden Harding','Nulla@egestasascelerisque.ca','Elk Grove HS','ECOSOC','China');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (38,'Hedley Deleon','ipsum.Suspendisse@Vivamus.com','Elk Grove HS','UN GA1','China');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (39,'Gavin Vega','malesuada.augue.ut@lectussitamet.org','Elk Grove HS','UN GA2','China');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (40,'Dominic Vasquez','lobortis.quam.a@Phasellusataugue.org','Elk Grove HS','IAEA','China');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (41,'Ezra Cherry','elit.elit@sitametultricies.co.uk','Elk Grove HS','Security Council','Morocco');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (42,'William Hardin','posuere.cubilia.Curae@ipsum.org','Elk Grove HS','ECOSOC','Morocco');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (43,'Mason Hebert','Praesent.luctus@odioPhasellusat.net','Elk Grove HS','UN GA1','Morocco');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (44,'Stuart Michael','mi@diamProin.ca','Elk Grove HS','UN GA2','Morocco');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (45,'Micah Bauer','orci.lobortis.augue@interdumligulaeu.co.uk','Elk Grove HS','IAEA','Morocco');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (46,'Merrill Bowen','tempor.augue.ac@Aliquam.co.uk','Sandburg','Security Council','Romania');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (47,'Price Holman','nisi.magna.sed@mauris.ca','Sandburg','UN GA1','Romania');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (48,'Ahmed Smith','vel@fringillaornareplacerat.com','Sandburg','UN GA2','Romania');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (49,'Francis Sharp','Nullam.suscipit.est@sapien.ca','Sandburg','IAEA','Romania');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (50,'Wade Cline','sit.amet@metus.com','Sandburg','Security Council','Italy');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (51,'Branden Benjamin','erat.vitae.risus@posuerecubiliaCurae.net','Sandburg','ECOSOC','Italy');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (52,'Ryan Fleming','turpis.nec.mauris@eliteratvitae.edu','Sandburg','UN GA1','Italy');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (53,'Luke Holden','Donec.consectetuer@orci.edu','Sandburg','UN GA2','Italy');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (54,'Dolan Forbes','Donec.fringilla@morbitristiquesenectus.ca','Sandburg','IAEA','Italy');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (55,'Elliott Mclean','purus.accumsan@blanditmattis.co.uk','St Ignatius College Prep','Security Council','Germany');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (56,'Ishmael Gonzalez','Proin.vel@commodo.net','St Ignatius College Prep','ECOSOC','Germany');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (57,'Zane Leblanc','auctor.velit.eget@tellus.com','St Ignatius College Prep','UN GA1','Germany');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (58,'Leo Armstrong','Suspendisse.sagittis.Nullam@acmieleifend.ca','St Ignatius College Prep','UN GA2','Germany');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (59,'Seth Lowe','in@venenatisvelfaucibus.ca','St Ignatius College Prep','IAEA','Germany');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (60,'Nehru Donaldson','Donec@orci.ca','St Ignatius College Prep','Security Council','Panama');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (61,'Nissim Garner','odio.Aliquam.vulputate@adipiscingligula.com','St Ignatius College Prep','ECOSOC','Panama');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (62,'Keane Shaffer','nostra@lobortis.org','St Ignatius College Prep','UN GA1','Panama');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (63,'Melvin Pearson','magna.Cras.convallis@convallis.co.uk','St Ignatius College Prep','UN GA2','Panama');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (64,'Vaughan Larsen','congue@habitant.co.uk','St Ignatius College Prep','IAEA','Panama');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (65,'Kermit Boyd','tristique.pharetra@nascetur.net','St Ignatius College Prep','Security Council','India');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (66,'Jerry Hunter','Mauris.nulla.Integer@pede.ca','St Ignatius College Prep','ECOSOC','India');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (67,'Burton Prince','ac.urna.Ut@sagittisNullamvitae.co.uk','St Ignatius College Prep','UN GA1','India');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (68,'Linus Everett','euismod.est.arcu@maurissapiencursus.net','St Ignatius College Prep','UN GA2','India');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (69,'Erich Humphrey','dolor.sit.amet@non.net','St Ignatius College Prep','IAEA','India');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (70,'Sean Hays','scelerisque.lorem.ipsum@facilisis.co.uk','North Side College Prep','Security Council','DPRK');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (71,'Carson Hartman','rutrum@ametmassa.com','North Side College Prep','ECOSOC','DPRK');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (72,'Rooney Hughes','eget.ipsum@vellectusCum.org','North Side College Prep','UN GA1','DPRK');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (73,'Hammett Olsen','iaculis.aliquet.diam@enim.net','North Side College Prep','UN GA2','DPRK');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (74,'Berk Dodson','risus.Donec.egestas@ametultriciessem.org','North Side College Prep','IAEA','DPRK');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (75,'Lev Carey','nec.mollis@non.co.uk','Jones College Prep','Security Council','Brazil');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (76,'Bert Weiss','nec@porttitor.org','Jones College Prep','ECOSOC','Brazil');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (77,'Malik Stanton','Phasellus.ornare.Fusce@utipsum.edu','Jones College Prep','UN GA1','Brazil');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (78,'Cadman Vasquez','sem.vitae.aliquam@a.org','Jones College Prep','UN GA2','Brazil');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (79,'Asher Velez','Nunc.pulvinar.arcu@Cras.co.uk','Jones College Prep','IAEA','Brazil');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (80,'Oren Mckee','eu.augue@et.edu','Lane Tech HS','Security Council','Nigeria');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (81,'Hop Mcdaniel','libero.Donec@iaculisnec.ca','Lane Tech HS','ECOSOC','Nigeria');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (82,'Wade Byers','felis.eget@lobortisaugue.edu','Lane Tech HS','UN GA1','Nigeria');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (83,'Paul Tate','sodales.elit.erat@etmalesuada.edu','Lane Tech HS','UN GA2','Nigeria');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (84,'Ronan Oneil','commodo.tincidunt@sodalespurus.co.uk','Lane Tech HS','IAEA','Nigeria');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (85,'Tad Sears','dictum@elitpedemalesuada.com','Lane Tech HS','Security Council','Chad');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (86,'Driscoll Meyers','Sed@volutpatnunc.co.uk','Lane Tech HS','ECOSOC','Chad');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (87,'Hunter Maxwell','velit.Aliquam@molestie.co.uk','Lane Tech HS','UN GA1','Chad');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (88,'Elton Allen','lorem@maurisIntegersem.ca','Lane Tech HS','UN GA2','Chad');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (89,'Kane Holman','urna.Vivamus@Praesent.net','Lane Tech HS','IAEA','Chad');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (90,'Colin Emerson','mauris@nectempusmauris.net','Lakeview HS','Security Council','Venezula');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (91,'Jared Beasley','Duis.gravida@Suspendisseseddolor.ca','Lakeview HS','ECOSOC','Venezula');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (92,'Kennan Mays','fermentum.convallis.ligula@semmollis.ca','Lakeview HS','UN GA1','Venezula');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (93,'Ashton Lambert','dolor@etrisus.co.uk','Lakeview HS','UN GA2','Venezula');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (94,'Zahir Todd','nec@nislarcu.edu','Lakeview HS','IAEA','Venezula');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (95,'Basil Moody','lorem.tristique@maurisa.ca','Lakeview HS','Security Council','Israel');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (96,'Conan Carr','Fusce@posuerecubiliaCurae.co.uk','Lakeview HS','ECOSOC','Israel');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (97,'Rooney Fry','libero.lacus@ategestas.com','Lakeview HS','UN GA1','Israel');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (98,'John Gutierrez','Phasellus@variusultricesmauris.com','Lakeview HS','UN GA2','Israel');
INSERT INTO delegates (id, name, email, school, committee, country) VALUES (99,'John Hyde','nonummy@posuerecubiliaCurae.org','Lakeview HS','IAEA','Israel');
